name: Deploy static content to Pages

on:
  push:
    branches: ["main"] # Запускается при пуше в main

permissions:
  contents: write # Разрешение на запись в репозиторий

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout
        uses: actions/checkout@v4

      # Шаг 2: Установка Node.js
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Укажите нужную версию Node.js

      # Шаг 3: Установка pnpm
      - name: Install PNPM
        run: npm install -g pnpm@8 # Укажите нужную версию pnpm

      # Шаг 4: Кэширование зависимостей pnpm
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-

      # Шаг 5: Установка зависимостей
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Шаг 6: Сборка проекта
      - name: Build
        run: pnpm run build

      # Шаг 7: Настройка Git для коммитов
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Шаг 8: Развертывание в ветку deploy
      - name: Push to deploy branch
        run: |
          git checkout --orphan deploy
          git rm -rf .
          git add -f dist
          git commit -m "Deploy to deploy branch"
          git push origin deploy --force
