name: Deploy static content to Pages

on:
  push:
    branches: ["main"] # Запускается при пуше в main

permissions:
  contents: write # Разрешение на запись в репозиторий

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to deploy branch
        run: |
          git checkout --orphan deploy
          git rm -rf .
          git add -f dist
          git commit -m "Deploy to deploy branch"
          git push origin deploy --force
